### ISSUE TITLE
How to use extrinsics utility.batch and utility.batchAll ?

### ISSUE THREAD

**Issue by poka-IT** [polkawallet-io/sdk#30]
I try to use `utility.batchAll()` with polkawallet_sdk.

This what i'm trying:

```
final txInfo = TxInfoData(
  'utility',
  'batchAll',
  sender,
);

final txOptions = [
  'universalDividend.claimUds()',
  'balances.transferKeepAlive($destAddress, $amountUnit)'
];

await sdk.api.tx
          .signAndSend(
            txInfo,
            txOptions,
            password,
          ).timeout(
            const Duration(seconds: 12),
            onTimeout: () => {},
          );
```

This this throw a timeout after 12s.
This 2 calls works fine one by one.
Do you have an example how to use batchAll here ?

**Comment by RomeroYang** [comment]
https://github.com/polkawallet-io/polkawallet_plugin_kusama/blob/master/lib/pages/staking/actions/stakePage.dart
