### ISSUE TITLE
Potential phishing address lookups

### ISSUE THREAD

**Issue by jacogr** [polkawallet-io/sdk#6]
**Is your feature request related to a problem? Please describe.**

Users in our ecosystem are consistently being scammed/phished. It would be great if this wallet can also integrate checking recipients against the phishing list https://polkadot.js.org/phishing/

**Describe the solution you'd like**

On sending, check the recipient against the list. If a known scam address, block/warn the user.

There are 2 solutions available,

- either use the JS libs to check addresses  - https://github.com/polkadot-js/phishing/tree/master/packages/phishing
- consume the address.json (via load) and do the checks - https://github.com/polkadot-js/phishing#integration

**Describe alternatives you've considered**

There are other solutions out in the wild, the above really focusses on Polkadot-ecosystem only.

**Additional context**

The above lists are really community maintained - as people report the URLs and addresses, they get added. If people do get scammed (sadly it does happen), they also get added. In the case of addresses, also do try to monitor the sites for address changes automatically and be proactive as scammers rotate addresses.

**Comment by RomeroYang** [comment]
feature implemented. https://github.com/polkawallet-io/sdk/blob/6a5a932cd8d2e433fd5c99cc70c695e7c393eb10/lib/polkawallet_sdk.dart#L61
