### ISSUE TITLE
Changing the plugin does not change the ss58 address

### ISSUE THREAD

**Issue by killbond007** [polkawallet-io/sdk#8]
**Describe the bug**
Changing the plugin does not change the ss58 address , Now only support [0, 2, 7, 42] 

**Screenshots**

https://user-images.githubusercontent.com/22051991/117531032-b3434f00-afe0-11eb-983d-bbac4fbf1042.mp4

**Additional context**

i think should add more ss58 in ss58List  ， （Can you help add value 6 in ss58List for bifrost ）

in https://github.com/polkawallet-io/sdk/blob/6644bb7e1959987d5913eb2200a2fd9574839675/lib/storage/keyring.dart

**Comment by RomeroYang** [comment]
fixed
